#!/bin/sh

. /usr/share/alterator/build/backend3.sh


XKB_DATADIR=/etc/alterator/xkb/data

KBD_CONFIG=/etc/sysconfig/keyboard.test
XKB_CONFIG=/etc/X11/xinit/Xkbmap.test

on_message()
{
	case "$in_action" in
		list)
			echo "("
			[ -d "$XKB_DATADIR"/"$in_lang" ] &&
			for i in "$XKB_DATADIR"/"$in_lang"/*.xkb ; do echo `basename $i`; done | 
				sed s,.xkb,,|
				sed 's,.*,("&"),'
			echo ")"
			;;
		write)
			install -Dpm644 "$XKB_DATADIR"/"$in__objects".xkb "$XKB_CONFIG"
			install -Dpm644 "$XKB_DATADIR"/"$in__objects".kbd "$KBD_CONFIG"
			/usr/bin/setxkbmap -option ""
			/usr/bin/setxkbmap `cat "$XKB_CONFIG"`
			echo "()"
			;;
	esac
}


message_loop


