#!/bin/sh

alterator_api_version=1
. alterator-sh-functions

DATADIR=/etc/alterator/sysconfig/
CONFIGDIR=/etc/sysconfig/

on_message()
{
	case "$in_action" in
		write)
			#TODO: use language information
			cp -af "$DATADIR/consolefont" "$CONFIGDIR/consolefont"
			;;
	esac
}

message_loop
