#!/bin/sh

. alterator-sh-functions

DATADIR=/etc/alterator/sysconfig/
CONFIGDIR=/etc/sysconfig/

on_message()
{
	case "$in_action" in
		write)
			#TODO: use language information
			cp -af "$DATADIR/consolefont" "$CONFIGDIR/consolefont"
			write_nop
			;;
		*)
			echo '#f'
			;;
	esac
}

message_loop
