#!/bin/sh

alterator_api_version=1
. alterator-sh-functions
. shell-config

CONFIGDIR=/etc/sysconfig/

on_message()
{
	case "$in_action" in
		write)
			#TODO: use language information
			shell_config_set "$CONFIGDIR/consolefont" SYSFONT UniCyrExt_8x16
			;;
	esac
}

message_loop
