NAME=proxy
DESCRIPTION="Proxy setup"

INSTALL=/usr/bin/install

all:
clean: clean-po
install: install-backend install-ui install-po

include /usr/share/alterator/build/po.mak
include /usr/share/alterator/build/ui2.mak
include /usr/share/alterator/build/backend.mak

